const products = [
        { id:1, category:"clubs", title:"Epic MAX Driver", marca: "Callaway", price:530, stock:10, description: "Artificial Intelligence Jailbreak Speed Frame stiffens the body from crown to sole and heel to toe for added stability and greater ball speed all across the club face", description2: "Flash Face SS21 design", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P155301/4-f.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P155301/1-f.jpg", img3:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P146445/4-f.jpg", img4:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P146445/2-f.jpg" },
        { id:2, category:"clubs", title:"Blueprint Irons", marca:"PING", price:1550, stock:14, description: "The multi-step forging process includes 50+ key inspections to ensure accuracy and precision.", description2:"Soft, shot after shot.", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P144794/1-f.jpg", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P144794/3-f.jpg" },
        { id:3, category:"clubs", title:"G425 MAX", marca: "PING", price:1770, stock:16, description: "T9S+ forged face generates more flex and speed for maximum distanceAdditional weight savings from refined Dragonfly Technology", description2: "Adjustable hosel", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P149225/f-callouts-149225.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P149225/1-f.jpg" },
        { id:4, category:"bags", title:"Opener Tour", marca: "TaylorMade", price:277, stock:10, description: "6-way top divider creates greater organization with a space for every club 3-point shoulder strap system for comfortable, balanced carrying", description2: "Limited Edition Tour Staff golf bag", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P158804/whitegreen-v-2-f.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P158804/f-whitegreen-v.jpg" },
        { id:5, category:"bags", title:"2020 DLX ", marca: "PING", price:375, stock:8, description: "Cart strap pass-through maintains access to pockets when the bag is strapped to a cart", description2: "Pockets: 15", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P148243/greyorange-x-2-f.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P148243/f-greyorange-x.jpg" },
        { id:6, category:"bags", title:"Callaway 2021 Chev", marca: "Callaway", price:"185", stock:6, description: "Sleek, versatile midsized stand bag with bold graphics", description2: "Pockets: 6", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P155383/yellowpurple-v-2-f.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P155383/f-yellowpurple-v.jpg" },
        { id:7, category:"accessories", title:"Bionic Glove", marca: "Bionic", price:30, stock:20, description: "Three dimensional finger pads wrap around fingers to stabilized grip Web and motion zones minimize bunching and improve motion", description2: "TableGrip with Natural Fit Golf Glove", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P57207/palm.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P57207/cfli-white.jpg" },
        { id:8, category:"accessories", title:"Tour X BOA Golf", marca: "FootJoy", price:230, stock:22, description: "BOA closure system lets you lock in your ideal fit without it coming loose Fast Twist 3.0™ cleat system with Softspikes® Pulsar® cleats", description2: "FootJoy's most stable golf shoe", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P145943/f-whitered-x.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P145943/whitered-x-2-f.jpg" },
        { id:9, category:"accessories", title:"TP5x Pack Ball", marca: "Tyltest", price:"45", stock:24, description: "Four increasingly stiff layers with HFM (High Flex Material) increase ball speed through greater reboundHFM is a material", description2: "TP5x Golf Ball", img:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P158982/white-v-3-f.jpg", img2:"https://www.tgw.com/wcsstore/CatalogAssetStore/Attachment/images/products/golf/P158982/f-white-v.jpg" },
];

export default products;
